spring.application.name=url-shortner-sb


spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=sandeep
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.show-sql= true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=${JWT_SECRET}
jwt.expiration=172800000


logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=TRACE

frontend.url=${FRONTEND_URL}
# frontend.url=${FRONTEND_URL:http://localhost:5173}